package cool.kolya

import com.squareup.javapoet.JavaFile
import com.squareup.javapoet.TypeSpec
import java.io.IOException
import java.nio.file.Path

abstract class CodeGenerator {

    companion object {
        const val EngineDirectPath = "src/main/java"
        const val EngineDirectPackage = "cool.kolya.engine.window.callback"
    }


    abstract fun generate()

    protected fun writeFile(typeSpec: TypeSpec, path: String, packageName: String) {
        val jFile = JavaFile.builder(packageName, typeSpec)
                .addFileComment("Autogenerated code")
                .build()
        try {
            jFile.writeTo(Path.of(path))
        } catch (ex: IOException) {
            ex.printStackTrace()
        }
    }
}