// Autogenerated code
package cool.kolya.engine;

import java.lang.Class;

import org.lwjgl.glfw.GLFW;
import org.lwjgl.glfw.GLFWCharCallbackI;
import org.lwjgl.glfw.GLFWCharModsCallbackI;
import org.lwjgl.glfw.GLFWCursorEnterCallbackI;
import org.lwjgl.glfw.GLFWCursorPosCallbackI;
import org.lwjgl.glfw.GLFWDropCallbackI;
import org.lwjgl.glfw.GLFWFramebufferSizeCallbackI;
import org.lwjgl.glfw.GLFWKeyCallbackI;
import org.lwjgl.glfw.GLFWMouseButtonCallbackI;
import org.lwjgl.glfw.GLFWScrollCallbackI;
import org.lwjgl.glfw.GLFWWindowCloseCallbackI;
import org.lwjgl.glfw.GLFWWindowContentScaleCallbackI;
import org.lwjgl.glfw.GLFWWindowFocusCallbackI;
import org.lwjgl.glfw.GLFWWindowIconifyCallbackI;
import org.lwjgl.glfw.GLFWWindowMaximizeCallbackI;
import org.lwjgl.glfw.GLFWWindowPosCallbackI;
import org.lwjgl.glfw.GLFWWindowRefreshCallbackI;
import org.lwjgl.glfw.GLFWWindowSizeCallbackI;

class Callbacks {
    static final Class<GLFWCharCallbackI> Char = GLFWCharCallbackI.class;

    static final Class<GLFWCharModsCallbackI> CharMods = GLFWCharModsCallbackI.class;

    static final Class<GLFWCursorEnterCallbackI> CursorEnter = GLFWCursorEnterCallbackI.class;

    static final Class<GLFWCursorPosCallbackI> CursorPos = GLFWCursorPosCallbackI.class;

    static final Class<GLFWDropCallbackI> Drop = GLFWDropCallbackI.class;

    static final Class<GLFWFramebufferSizeCallbackI> FramebufferSize = GLFWFramebufferSizeCallbackI.class;

    static final Class<GLFWKeyCallbackI> Key = GLFWKeyCallbackI.class;

    static final Class<GLFWMouseButtonCallbackI> MouseButton = GLFWMouseButtonCallbackI.class;

    static final Class<GLFWScrollCallbackI> Scroll = GLFWScrollCallbackI.class;

    static final Class<GLFWWindowCloseCallbackI> WindowClose = GLFWWindowCloseCallbackI.class;

    static final Class<GLFWWindowContentScaleCallbackI> WindowContentScale = GLFWWindowContentScaleCallbackI.class;

    static final Class<GLFWWindowFocusCallbackI> WindowFocus = GLFWWindowFocusCallbackI.class;

    static final Class<GLFWWindowIconifyCallbackI> WindowIconify = GLFWWindowIconifyCallbackI.class;

    static final Class<GLFWWindowMaximizeCallbackI> WindowMaximize = GLFWWindowMaximizeCallbackI.class;

    static final Class<GLFWWindowPosCallbackI> WindowPos = GLFWWindowPosCallbackI.class;

    static final Class<GLFWWindowRefreshCallbackI> WindowRefresh = GLFWWindowRefreshCallbackI.class;

    static final Class<GLFWWindowSizeCallbackI> WindowSize = GLFWWindowSizeCallbackI.class;

    static void initialize(WindowCallbackListener callbackListener, long windowPointer) {
        GLFW.glfwSetCharCallback(windowPointer, ((arg0, arg1) ->
                callbackListener.listenCallback(Char, handler -> handler.invoke(arg0, arg1))));
        GLFW.glfwSetCharModsCallback(windowPointer, ((arg0, arg1, arg2) ->
                callbackListener.listenCallback(CharMods, handler -> handler.invoke(arg0, arg1, arg2))));
        GLFW.glfwSetCursorEnterCallback(windowPointer, ((arg0, arg1) ->
                callbackListener.listenCallback(CursorEnter, handler -> handler.invoke(arg0, arg1))));
        GLFW.glfwSetCursorPosCallback(windowPointer, ((arg0, arg1, arg2) ->
                callbackListener.listenCallback(CursorPos, handler -> handler.invoke(arg0, arg1, arg2))));
        GLFW.glfwSetDropCallback(windowPointer, ((arg0, arg1, arg2) ->
                callbackListener.listenCallback(Drop, handler -> handler.invoke(arg0, arg1, arg2))));
        GLFW.glfwSetFramebufferSizeCallback(windowPointer, ((arg0, arg1, arg2) ->
                callbackListener.listenCallback(FramebufferSize, handler -> handler.invoke(arg0, arg1, arg2))));
        GLFW.glfwSetKeyCallback(windowPointer, ((arg0, arg1, arg2, arg3, arg4) ->
                callbackListener.listenCallback(Key, handler -> handler.invoke(arg0, arg1, arg2, arg3, arg4))));
        GLFW.glfwSetMouseButtonCallback(windowPointer, ((arg0, arg1, arg2, arg3) ->
                callbackListener.listenCallback(MouseButton, handler -> handler.invoke(arg0, arg1, arg2, arg3))));
        GLFW.glfwSetScrollCallback(windowPointer, ((arg0, arg1, arg2) ->
                callbackListener.listenCallback(Scroll, handler -> handler.invoke(arg0, arg1, arg2))));
        GLFW.glfwSetWindowCloseCallback(windowPointer, ((arg0) ->
                callbackListener.listenCallback(WindowClose, handler -> handler.invoke(arg0))));
        GLFW.glfwSetWindowContentScaleCallback(windowPointer, ((arg0, arg1, arg2) ->
                callbackListener.listenCallback(WindowContentScale, handler -> handler.invoke(arg0, arg1, arg2))));
        GLFW.glfwSetWindowFocusCallback(windowPointer, ((arg0, arg1) ->
                callbackListener.listenCallback(WindowFocus, handler -> handler.invoke(arg0, arg1))));
        GLFW.glfwSetWindowIconifyCallback(windowPointer, ((arg0, arg1) ->
                callbackListener.listenCallback(WindowIconify, handler -> handler.invoke(arg0, arg1))));
        GLFW.glfwSetWindowMaximizeCallback(windowPointer, ((arg0, arg1) ->
                callbackListener.listenCallback(WindowMaximize, handler -> handler.invoke(arg0, arg1))));
        GLFW.glfwSetWindowPosCallback(windowPointer, ((arg0, arg1, arg2) ->
                callbackListener.listenCallback(WindowPos, handler -> handler.invoke(arg0, arg1, arg2))));
        GLFW.glfwSetWindowRefreshCallback(windowPointer, ((arg0) ->
                callbackListener.listenCallback(WindowRefresh, handler -> handler.invoke(arg0))));
        GLFW.glfwSetWindowSizeCallback(windowPointer, ((arg0, arg1, arg2) ->
                callbackListener.listenCallback(WindowSize, handler -> handler.invoke(arg0, arg1, arg2))));
    }
}
